import type { Team, Account, User, Module, Workflow, Asset, Scene, Widget, PaginatedResponse } from '@/types';

export const mockUser: User = {
  id: 'user-1',
  email: 'alex@streamcontrol.io',
  displayName: 'Alex Chen',
  role: 'owner',
  teamIds: ['team-1'],
  accountIds: ['account-1', 'account-2'],
  createdAt: '2024-01-01T00:00:00Z',
};

export const mockTeams: Team[] = [
  { id: 'team-1', name: 'Demo Team', slug: 'demo-team', ownerId: 'user-1', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'team-2', name: 'Production Team', slug: 'production-team', ownerId: 'user-1', createdAt: '2024-01-15T00:00:00Z' },
];

export const mockAccounts: Account[] = [
  { id: 'account-1', name: 'Main Channel', slug: 'main-channel', teamId: 'team-1', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'account-2', name: 'Gaming Channel', slug: 'gaming-channel', teamId: 'team-1', createdAt: '2024-01-05T00:00:00Z' },
];

export const mockModules: Module[] = [
  {
    id: 'mod-1',
    name: 'Twitch Integration',
    slug: 'twitch-integration',
    description: 'Connect your Twitch channel with comprehensive API support for chat, events, and channel points.',
    category: 'Integrations',
    version: '2.1.0',
    author: 'StreamControl Team',
    isInstalled: true,
    isEnabled: true,
    triggers: [
      { id: 'chat-message', name: 'Chat Message', description: 'Triggered when a chat message is received', parameters: [] },
      { id: 'new-follower', name: 'New Follower', description: 'Triggered when someone follows the channel', parameters: [] },
    ],
    actions: [
      { id: 'send-chat', name: 'Send Chat Message', description: 'Send a message to chat', parameters: [] },
    ],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'mod-2',
    name: 'Chat Commands',
    slug: 'chat-commands',
    description: 'Create custom chat commands with variables, cooldowns, and permission levels.',
    category: 'Chat',
    version: '1.5.2',
    author: 'StreamControl Team',
    isInstalled: true,
    isEnabled: true,
    triggers: [],
    actions: [],
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-08T00:00:00Z',
  },
  {
    id: 'mod-3',
    name: 'Alert Box Pro',
    slug: 'alert-box-pro',
    description: 'Advanced alert system with custom animations, sounds, and TTS support for all event types.',
    category: 'Alerts',
    version: '3.0.1',
    author: 'StreamControl Team',
    isInstalled: true,
    isEnabled: false,
    triggers: [],
    actions: [],
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-12T00:00:00Z',
  },
  {
    id: 'mod-4',
    name: 'Sound Effects',
    slug: 'sound-effects',
    description: 'Trigger sound effects from chat commands, channel points, or workflow events.',
    category: 'Audio',
    version: '1.2.0',
    author: 'Community',
    isInstalled: false,
    isEnabled: false,
    triggers: [],
    actions: [],
    createdAt: '2024-01-04T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'mod-5',
    name: 'Media Controls',
    slug: 'media-controls',
    description: 'Let viewers control media playback through chat commands and channel point redemptions.',
    category: 'Media',
    version: '2.0.0',
    author: 'Community',
    isInstalled: false,
    isEnabled: false,
    triggers: [],
    actions: [],
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-09T00:00:00Z',
  },
  {
    id: 'mod-6',
    name: 'Auto Moderation',
    slug: 'auto-moderation',
    description: 'Intelligent chat moderation with customizable filters, warnings, and timeout automation.',
    category: 'Chat',
    version: '1.8.0',
    author: 'StreamControl Team',
    isInstalled: false,
    isEnabled: false,
    triggers: [],
    actions: [],
    createdAt: '2024-01-06T00:00:00Z',
    updatedAt: '2024-01-11T00:00:00Z',
  },
  {
    id: 'mod-7',
    name: 'Viewer Games',
    slug: 'viewer-games',
    description: 'Interactive mini-games for your viewers including predictions, trivia, and gambling.',
    category: 'Automation',
    version: '1.0.0',
    author: 'Community',
    isInstalled: false,
    isEnabled: false,
    triggers: [],
    actions: [],
    createdAt: '2024-01-07T00:00:00Z',
    updatedAt: '2024-01-07T00:00:00Z',
  },
  {
    id: 'mod-8',
    name: 'Scene Transitions',
    slug: 'scene-transitions',
    description: 'Beautiful animated transitions between scenes with customizable effects.',
    category: 'Effects',
    version: '1.3.0',
    author: 'Community',
    isInstalled: false,
    isEnabled: false,
    triggers: [],
    actions: [],
    createdAt: '2024-01-08T00:00:00Z',
    updatedAt: '2024-01-06T00:00:00Z',
  },
];

export const mockWorkflows: Workflow[] = [
  {
    id: 'wf-1',
    name: 'Chat Commands Handler',
    description: 'Responds to custom chat commands with configurable responses and cooldowns.',
    accountId: 'account-1',
    isEnabled: true,
    nodes: [
      { id: 'n1', type: 'trigger', moduleId: 'mod-1', definitionId: 'chat-message', position: { x: 100, y: 150 }, data: { label: 'Chat Message', description: 'When message received', icon: 'MessageSquare', parameters: {} } },
      { id: 'n2', type: 'condition', moduleId: 'core', definitionId: 'condition', position: { x: 400, y: 100 }, data: { label: 'Check Command', description: 'If starts with !', icon: 'Filter', parameters: {} } },
      { id: 'n3', type: 'action', moduleId: 'mod-1', definitionId: 'send-chat', position: { x: 700, y: 50 }, data: { label: 'Send Response', description: 'Reply in chat', icon: 'MessageSquare', parameters: {} } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n2', target: 'n3' },
    ],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'wf-2',
    name: 'Follow Alert System',
    description: 'Triggers alerts and sounds when new followers join the channel.',
    accountId: 'account-1',
    isEnabled: true,
    nodes: [],
    edges: [],
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-09T00:00:00Z',
  },
  {
    id: 'wf-3',
    name: 'Donation Processing',
    description: 'Handles donation events with TTS, overlays, and thank you messages.',
    accountId: 'account-1',
    isEnabled: true,
    nodes: [],
    edges: [],
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-08T00:00:00Z',
  },
  {
    id: 'wf-4',
    name: 'Channel Point Rewards',
    description: 'Manages custom channel point redemptions and their actions.',
    accountId: 'account-1',
    isEnabled: true,
    nodes: [],
    edges: [],
    createdAt: '2024-01-04T00:00:00Z',
    updatedAt: '2024-01-07T00:00:00Z',
  },
  {
    id: 'wf-5',
    name: 'Raid Handler',
    description: 'Welcomes raiders with special messages and scene transitions.',
    accountId: 'account-1',
    isEnabled: false,
    nodes: [],
    edges: [],
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-06T00:00:00Z',
  },
  {
    id: 'wf-6',
    name: 'Subscriber Celebration',
    description: 'Special effects and messages for new and recurring subscribers.',
    accountId: 'account-1',
    isEnabled: true,
    nodes: [],
    edges: [],
    createdAt: '2024-01-06T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
];

export const mockAssets: Asset[] = [
  { id: 'asset-1', name: 'alert-sound.mp3', type: 'audio', mimeType: 'audio/mp3', size: 245000, url: '/assets/alert-sound.mp3', accountId: 'account-1', tags: ['alerts', 'sounds'], createdAt: '2024-01-10T00:00:00Z', updatedAt: '2024-01-10T00:00:00Z' },
  { id: 'asset-2', name: 'follow-animation.webm', type: 'video', mimeType: 'video/webm', size: 1240000, url: '/assets/follow-animation.webm', accountId: 'account-1', tags: ['animations', 'follow'], createdAt: '2024-01-09T00:00:00Z', updatedAt: '2024-01-09T00:00:00Z' },
  { id: 'asset-3', name: 'overlay-frame.png', type: 'image', mimeType: 'image/png', size: 520000, url: '/assets/overlay-frame.png', accountId: 'account-1', tags: ['overlay', 'frame'], createdAt: '2024-01-08T00:00:00Z', updatedAt: '2024-01-08T00:00:00Z' },
  { id: 'asset-4', name: 'donation-chime.wav', type: 'audio', mimeType: 'audio/wav', size: 180000, url: '/assets/donation-chime.wav', accountId: 'account-1', tags: ['donations', 'sounds'], createdAt: '2024-01-07T00:00:00Z', updatedAt: '2024-01-07T00:00:00Z' },
  { id: 'asset-5', name: 'sub-badge-tier1.png', type: 'image', mimeType: 'image/png', size: 45000, url: '/assets/sub-badge-tier1.png', accountId: 'account-1', tags: ['badges', 'subscriber'], createdAt: '2024-01-06T00:00:00Z', updatedAt: '2024-01-06T00:00:00Z' },
  { id: 'asset-6', name: 'sub-badge-tier2.png', type: 'image', mimeType: 'image/png', size: 48000, url: '/assets/sub-badge-tier2.png', accountId: 'account-1', tags: ['badges', 'subscriber'], createdAt: '2024-01-06T00:00:00Z', updatedAt: '2024-01-06T00:00:00Z' },
  { id: 'asset-7', name: 'sub-badge-tier3.png', type: 'image', mimeType: 'image/png', size: 52000, url: '/assets/sub-badge-tier3.png', accountId: 'account-1', tags: ['badges', 'subscriber'], createdAt: '2024-01-06T00:00:00Z', updatedAt: '2024-01-06T00:00:00Z' },
  { id: 'asset-8', name: 'intro-video.mp4', type: 'video', mimeType: 'video/mp4', size: 15240000, url: '/assets/intro-video.mp4', accountId: 'account-1', tags: ['intro', 'video'], createdAt: '2024-01-05T00:00:00Z', updatedAt: '2024-01-05T00:00:00Z' },
  { id: 'asset-9', name: 'background-music.mp3', type: 'audio', mimeType: 'audio/mp3', size: 4500000, url: '/assets/background-music.mp3', accountId: 'account-1', tags: ['music', 'background'], createdAt: '2024-01-04T00:00:00Z', updatedAt: '2024-01-04T00:00:00Z' },
  { id: 'asset-10', name: 'channel-logo.svg', type: 'image', mimeType: 'image/svg+xml', size: 12000, url: '/assets/channel-logo.svg', accountId: 'account-1', tags: ['branding', 'logo'], createdAt: '2024-01-03T00:00:00Z', updatedAt: '2024-01-03T00:00:00Z' },
  { id: 'asset-11', name: 'emote-pack.zip', type: 'other', mimeType: 'application/zip', size: 2400000, url: '/assets/emote-pack.zip', accountId: 'account-1', tags: ['emotes'], createdAt: '2024-01-02T00:00:00Z', updatedAt: '2024-01-02T00:00:00Z' },
  { id: 'asset-12', name: 'custom-font.woff2', type: 'font', mimeType: 'font/woff2', size: 85000, url: '/assets/custom-font.woff2', accountId: 'account-1', tags: ['fonts', 'typography'], createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
];

export const mockScenes: Scene[] = [
  {
    id: 'scene-1',
    name: 'Main Overlay',
    description: 'Primary streaming overlay with chat and alerts',
    accountId: 'account-1',
    width: 1920,
    height: 1080,
    backgroundColor: 'transparent',
    widgets: [
      { id: 'w1', type: 'text', name: 'Stream Title', position: { x: 50, y: 50 }, size: { width: 400, height: 60 }, rotation: 0, opacity: 100, zIndex: 3, locked: false, visible: true, properties: { text: 'Welcome to the Stream!', fontSize: 32, fontFamily: 'Inter', color: '#ffffff', align: 'left' } },
      { id: 'w2', type: 'image', name: 'Logo', position: { x: 1720, y: 50 }, size: { width: 150, height: 150 }, rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true, properties: { src: '/logo.png' } },
      { id: 'w3', type: 'chat', name: 'Chat Widget', position: { x: 1520, y: 600 }, size: { width: 380, height: 400 }, rotation: 0, opacity: 80, zIndex: 1, locked: false, visible: true, properties: {} },
      { id: 'w4', type: 'shape', name: 'Background Box', position: { x: 30, y: 30 }, size: { width: 440, height: 100 }, rotation: 0, opacity: 50, zIndex: 0, locked: false, visible: true, properties: { fill: '#000000', borderRadius: 8 } },
    ],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'scene-2',
    name: 'BRB Screen',
    description: 'Be right back screen with countdown',
    accountId: 'account-1',
    width: 1920,
    height: 1080,
    backgroundColor: '#1a1a2e',
    widgets: [
      { id: 'w5', type: 'text', name: 'BRB Text', position: { x: 760, y: 400 }, size: { width: 400, height: 80 }, rotation: 0, opacity: 100, zIndex: 2, locked: false, visible: true, properties: { text: 'Be Right Back', fontSize: 48, fontFamily: 'Inter', color: '#ffffff', align: 'center' } },
      { id: 'w6', type: 'timer', name: 'Countdown', position: { x: 860, y: 500 }, size: { width: 200, height: 60 }, rotation: 0, opacity: 100, zIndex: 1, locked: false, visible: true, properties: { duration: 300 } },
    ],
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-08T00:00:00Z',
  },
  {
    id: 'scene-3',
    name: 'Starting Soon',
    description: 'Pre-stream countdown screen',
    accountId: 'account-1',
    width: 1920,
    height: 1080,
    backgroundColor: '#16213e',
    widgets: [],
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
];

export function paginate<T>(items: T[], page: number, pageSize: number): PaginatedResponse<T> {
  const totalItems = items.length;
  const totalPages = Math.ceil(totalItems / pageSize);
  const start = (page - 1) * pageSize;
  const end = start + pageSize;
  
  return {
    data: items.slice(start, end),
    pagination: {
      page,
      pageSize,
      totalItems,
      totalPages,
      hasNext: page < totalPages,
      hasPrev: page > 1,
    },
  };
}

export function delay(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}
