import type { InboundWebhookResponse } from "@woofx3/api";
import type { CallbackEnvelope, CallbackEvent } from "@woofx3/api/webhooks";
import { EngineEventType } from "@woofx3/api/webhooks";
import { httpRouter } from "convex/server";
import { internal } from "./_generated/api";
import { httpAction } from "./_generated/server";
import { auth } from "./auth";
import { buildBrowserSourcePlaceholderHtml, buildBrowserSourceRedirect } from "./lib/browserSourceHtml";
import { escapeDollarKeys } from "./lib/dollarKeys";
import { createEngineRpcSession, type EngineApi } from "./lib/engineInstanceUrl";
import { parseInboundWebhookPath } from "./lib/inboundWebhookPath";
import {
  buildForwardedRequest,
  EngineTimeoutError,
  MAX_INBOUND_BODY_BYTES,
  toHttpResponse,
  withEngineTimeout,
} from "./lib/inboundWebhookRelay";
import { executeMacroPlan, MacroRunRefused, valuesToPairs } from "./lib/macroExecution";
import {
  hashTriggerToken,
  isBrowserRequest,
  MACRO_TRIGGER_PATH,
  MACRO_TRIGGER_PATH_PREFIX,
  MAX_TRIGGER_BODY_BYTES,
  parseTriggerValues,
  resolveTriggerToken,
  triggerRefusalResponse,
} from "./lib/macroTrigger";
import { SIGNATURE_HEADER, verifySignature } from "./lib/maintenanceSignature";
import type { OAuthErrorCode } from "./lib/oauthErrors";
import { generateOpaqueToken, hashOpaqueToken, isOpaqueToken } from "./lib/oauthHandoff";
import { withQuery } from "./lib/safeRedirect";
import { isCurrentSceneUrl } from "./lib/sceneOverlayUrl";
import { SESSION_SUMMARY_EVENT_TYPE } from "./lib/sessionSummary";
import { canManageTwitchLink } from "./lib/twitchLinkPolicy";
import { widgetCanonicalKey } from "./lib/widgetKey";
import { WORKFLOW_HEALTH_CHANGED_EVENT_TYPE, WORKFLOW_HEALTH_SNAPSHOT_EVENT_TYPE } from "./lib/workflowHealth";
import { logger } from "./logger";
import { canonicalIdForStorageKey } from "./resourceValues";
import "./browserSource";
import "./moduleWebhook";

const http = httpRouter();

const CORS_HEADERS: Record<string, string> =
  process.env.CORS_ENABLED === "true"
    ? {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, POST, PATCH, DELETE, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type, Authorization",
      }
    : {};

function corsJson(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...CORS_HEADERS },
  });
}

const preflightHandler = httpAction(async () => {
  if (process.env.CORS_ENABLED !== "true") {
    return new Response(null, { status: 404 });
  }
  return new Response(null, { status: 204, headers: CORS_HEADERS });
});

// Registers /.well-known/jwks.json, /.well-known/openid-configuration, and
// Password provider routes. Must come before custom routes.
auth.addHttpRoutes(http);

function assert(condition: unknown, msg: string): asserts condition {
  if (!condition) throw new Error(`[twitch-oauth] ASSERT FAILED: ${msg}`);
}

type LogDetail = Record<string, string | number | boolean | string[]>;

function redirect(location: string): Response {
  return new Response(null, { status: 302, headers: { Location: location } });
}

/**
 * Back to the callback page with an error code to show. Only the code travels
 * in the URL; the page maps it to fixed text (lib/oauthErrors.ts), and any
 * detail goes to the log without provider response bodies or tokens.
 */
function signInErrorRedirect(siteUrl: string, code: OAuthErrorCode, detail: LogDetail = {}): Response {
  logger.error("twitch sign-in failed", { code, ...detail });
  return redirect(`${siteUrl}/auth/twitch/callback?${new URLSearchParams({ error: code })}`);
}

/**
 * The connect flavour of `signInErrorRedirect`: the creator is signed in
 * already, so the page offers a way back to where they started rather than
 * the login page.
 */
function connectErrorRedirect(siteUrl: string, redirectTo: string, code: OAuthErrorCode, detail: LogDetail = {}) {
  logger.error("twitch connect failed", { code, ...detail });
  const params = new URLSearchParams({ mode: "connect", error: code, redirect_to: redirectTo });
  return redirect(`${siteUrl}/auth/twitch/callback?${params}`);
}

/** Field names only: a token response body carries the tokens themselves. */
function fieldNames(body: unknown): string[] {
  if (typeof body !== "object" || body === null) {
    return [];
  }
  return Object.keys(body);
}

http.route({
  path: "/api/auth/twitch/start",
  method: "GET",
  handler: httpAction(async (ctx, request) => {
    assert(process.env.SITE_URL, "SITE_URL env var is not set");
    assert(process.env.AUTH_TWITCH_ID, "AUTH_TWITCH_ID env var is not set");
    assert(process.env.AUTH_TWITCH_REDIRECT_URI, "AUTH_TWITCH_REDIRECT_URI env var is not set");

    const url = new URL(request.url);
    const redirectTo = url.searchParams.get("redirect_to") ?? "/";
    // Generated by the SPA tab that is signing in and kept there
    // (client/src/lib/twitch-sign-in.ts); the sign-in completes only when that
    // tab presents it again.
    const nonce = url.searchParams.get("nonce");
    if (!isOpaqueToken(nonce)) {
      return signInErrorRedirect(process.env.SITE_URL, "sign_in_not_started_here");
    }
    const state = crypto.randomUUID();

    await ctx.runMutation(internal.twitchAuth.storeState, {
      state,
      redirectTo,
      nonceHash: await hashOpaqueToken(nonce),
    });

    const params = new URLSearchParams({
      client_id: process.env.AUTH_TWITCH_ID,
      redirect_uri: process.env.AUTH_TWITCH_REDIRECT_URI,
      response_type: "code",
      scope: "user:read:email",
      state,
    });

    logger.info("redirecting to twitch for sign-in");
    return redirect(`https://id.twitch.tv/oauth2/authorize?${params}`);
  }),
});

http.route({
  path: "/api/auth/twitch/callback",
  method: "GET",
  handler: httpAction(async (ctx, request) => {
    assert(process.env.SITE_URL, "SITE_URL env var is not set");
    assert(process.env.AUTH_TWITCH_ID, "AUTH_TWITCH_ID env var is not set");
    assert(process.env.AUTH_TWITCH_SECRET, "AUTH_TWITCH_SECRET env var is not set");
    assert(process.env.AUTH_TWITCH_REDIRECT_URI, "AUTH_TWITCH_REDIRECT_URI env var is not set");

    const siteUrl = process.env.SITE_URL;
    const url = new URL(request.url);
    const code = url.searchParams.get("code");
    const state = url.searchParams.get("state");

    logger.info("callback received", { hasCode: !!code, hasState: !!state });

    if (!state) {
      return signInErrorRedirect(siteUrl, "missing_params", { hasCode: !!code });
    }
    const stateResult = await ctx.runMutation(internal.twitchAuth.validateAndConsumeState, { state });
    if (!stateResult) {
      return signInErrorRedirect(siteUrl, "invalid_state");
    }
    const { redirectTo, instanceId, userId, nonceHash } = stateResult;
    const fail = (errorCode: OAuthErrorCode, detail: LogDetail = {}): Response =>
      instanceId
        ? connectErrorRedirect(siteUrl, redirectTo, errorCode, detail)
        : signInErrorRedirect(siteUrl, errorCode, detail);

    if (!code) {
      // Twitch answers a declined consent with ?error=access_denied and no code.
      return fail(url.searchParams.get("error") === "access_denied" ? "access_denied" : "missing_params");
    }

    // An integration state is minted only by twitchIntegration.startConnect,
    // for an owner or admin. Checked again here because a role can be taken
    // away in the minutes the creator spends on Twitch's consent page, and
    // once more when the connect is finished.
    if (instanceId) {
      if (!userId) {
        return fail("not_started_by_user");
      }
      const role = await ctx.runQuery(internal.instances.memberRole, { instanceId, userId });
      if (!canManageTwitchLink(role)) {
        return fail("not_permitted");
      }
    } else if (!nonceHash) {
      return fail("sign_in_not_started_here");
    }

    logger.info("state valid, exchanging code", { isIntegration: !!instanceId });

    const tokenRes = await fetch("https://id.twitch.tv/oauth2/token", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        client_id: process.env.AUTH_TWITCH_ID,
        client_secret: process.env.AUTH_TWITCH_SECRET,
        code,
        grant_type: "authorization_code",
        redirect_uri: process.env.AUTH_TWITCH_REDIRECT_URI,
      }),
    });

    if (!tokenRes.ok) {
      return fail("token_exchange_failed", { status: tokenRes.status });
    }

    const tokenData = await tokenRes.json();
    if (typeof tokenData?.access_token !== "string" || tokenData.access_token.length === 0) {
      return fail("token_exchange_failed", { fields: fieldNames(tokenData) });
    }
    logger.info("token exchange ok");

    const userRes = await fetch("https://api.twitch.tv/helix/users", {
      headers: {
        Authorization: `Bearer ${tokenData.access_token}`,
        "Client-Id": process.env.AUTH_TWITCH_ID,
      },
    });

    if (!userRes.ok) {
      return fail("profile_fetch_failed", { status: userRes.status });
    }

    const { data } = await userRes.json();
    if (!Array.isArray(data) || data.length === 0) {
      return fail("profile_fetch_failed", { reason: "empty user data" });
    }
    const twitchUser = data[0];
    logger.info("got twitch user", { login: twitchUser.login, id: twitchUser.id });

    if (instanceId && userId) {
      if (typeof tokenData.refresh_token !== "string" || typeof tokenData.expires_in !== "number") {
        return fail("token_exchange_failed", { fields: fieldNames(tokenData) });
      }
      const scopes: string[] = Array.isArray(tokenData.scope)
        ? tokenData.scope
        : String(tokenData.scope ?? "").split(" ");

      // The result is held for the user who started the connect, not written
      // here: this request runs in whichever browser Twitch redirected, which
      // is not necessarily theirs.
      const handoffCode = generateOpaqueToken();
      await ctx.runMutation(internal.oauthConnectHandoff.store, {
        codeHash: await hashOpaqueToken(handoffCode),
        provider: "twitch",
        userId,
        instanceId,
        redirectTo,
        twitch: {
          platformUserId: twitchUser.id,
          platformUsername: twitchUser.display_name || twitchUser.login,
          profileImageUrl: twitchUser.profile_image_url ?? undefined,
          accessToken: tokenData.access_token,
          refreshToken: tokenData.refresh_token,
          expiresAt: Date.now() + tokenData.expires_in * 1000,
          scopes,
        },
      });

      logger.info("redirecting to frontend to finish the connect");
      const params = new URLSearchParams({ mode: "connect", code: handoffCode, redirect_to: redirectTo });
      return redirect(`${siteUrl}/auth/twitch/callback?${params}`);
    }

    assert(nonceHash, "sign-in state without a nonce hash");
    const token = await ctx.runMutation(internal.twitchAuth.storePendingAuth, {
      twitchId: twitchUser.id,
      displayName: twitchUser.display_name,
      email: twitchUser.email ?? "",
      profileImage: twitchUser.profile_image_url ?? "",
      nonceHash,
    });

    logger.info("redirecting to frontend to finish sign-in");
    const params = new URLSearchParams({ token, redirect_to: redirectTo });
    return redirect(`${siteUrl}/auth/twitch/callback?${params}`);
  }),
});

function moduleIntegrationErrorRedirect(
  siteUrl: string,
  redirectTo: string,
  integration: string,
  code: OAuthErrorCode,
  detail: LogDetail = {}
): Response {
  logger.error("module integration oauth failed", { integration, code, ...detail });
  return redirect(`${siteUrl}${withQuery(redirectTo, { integration, status: "error", error: code }, "/modules")}`);
}

http.route({
  path: "/api/integrations/spotify/callback",
  method: "GET",
  handler: httpAction(async (ctx, request) => {
    assert(process.env.SPOTIFY_REDIRECT_URI, "SPOTIFY_REDIRECT_URI env var is not set");
    const siteUrl = process.env.SITE_URL ?? "";

    const url = new URL(request.url);
    const code = url.searchParams.get("code");
    const state = url.searchParams.get("state");

    if (!state) {
      // No redirectTo is known without a valid state row, so /modules is the
      // best available destination.
      return moduleIntegrationErrorRedirect(siteUrl, "/modules", "spotify", "missing_params");
    }

    const stateResult = await ctx.runMutation(internal.moduleIntegrationState.validateAndConsumeState, { state });
    if (!stateResult || stateResult.integration !== "spotify") {
      return moduleIntegrationErrorRedirect(siteUrl, "/modules", "spotify", "invalid_state");
    }
    const { instanceId, moduleId, redirectTo, userId, data } = stateResult;
    if (!code) {
      const declined = url.searchParams.get("error") === "access_denied";
      return moduleIntegrationErrorRedirect(
        siteUrl,
        redirectTo,
        "spotify",
        declined ? "access_denied" : "missing_params"
      );
    }
    // spotifyConnect.start mints states only for a member; checked again in
    // case the membership went away while the user was on Spotify's page, and
    // once more when the connect is finished.
    if (!userId) {
      return moduleIntegrationErrorRedirect(siteUrl, redirectTo, "spotify", "not_started_by_user");
    }
    if ((await ctx.runQuery(internal.instances.memberRole, { instanceId, userId })) === null) {
      return moduleIntegrationErrorRedirect(siteUrl, redirectTo, "spotify", "not_permitted");
    }
    const { clientId, codeVerifier } = (data ?? {}) as { clientId?: string; codeVerifier?: string };
    if (!clientId || !codeVerifier) {
      return moduleIntegrationErrorRedirect(siteUrl, redirectTo, "spotify", "invalid_state", {
        reason: "malformed state data",
      });
    }

    const tokenRes = await fetch("https://accounts.spotify.com/api/token", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        grant_type: "authorization_code",
        code,
        redirect_uri: process.env.SPOTIFY_REDIRECT_URI,
        client_id: clientId,
        code_verifier: codeVerifier,
      }),
    });

    if (!tokenRes.ok) {
      return moduleIntegrationErrorRedirect(siteUrl, redirectTo, "spotify", "token_exchange_failed", {
        status: tokenRes.status,
      });
    }

    const tokenData = await tokenRes.json();
    if (typeof tokenData?.access_token !== "string" || typeof tokenData?.refresh_token !== "string") {
      return moduleIntegrationErrorRedirect(siteUrl, redirectTo, "spotify", "token_exchange_failed", {
        fields: fieldNames(tokenData),
      });
    }

    // Held for the member who started the connect rather than written here;
    // see the Twitch callback above.
    const handoffCode = generateOpaqueToken();
    await ctx.runMutation(internal.oauthConnectHandoff.store, {
      codeHash: await hashOpaqueToken(handoffCode),
      provider: "spotify",
      userId,
      instanceId,
      moduleId,
      redirectTo,
      spotify: { clientId, authToken: tokenData.access_token, refreshToken: tokenData.refresh_token },
    });

    logger.info("spotify authorized, redirecting to frontend to finish", { instanceId, moduleId });
    return redirect(
      `${siteUrl}${withQuery(redirectTo, { integration: "spotify", connect_code: handoffCode }, "/modules")}`
    );
  }),
});

http.route({ path: "/api/webhooks/woofx3", method: "OPTIONS", handler: preflightHandler });
http.route({
  path: "/api/webhooks/woofx3",
  method: "POST",
  handler: httpAction(async (ctx, request) => {
    const payload = await request.json();

    logger.info("webhook: incoming request", {
      type: payload.type,
      url: request.url,
    });

    if (!payload.type) {
      logger.warn("webhook: missing type field", { payload: JSON.stringify(payload) });
      return corsJson({ error: "Missing required field: type" }, 400);
    }

    // Validate webhook secret (callbackToken) via Bearer token
    const authHeader = request.headers.get("Authorization");
    const providedSecret = authHeader?.replace("Bearer ", "");
    if (!providedSecret) {
      logger.warn("webhook: missing Authorization header");
      return corsJson({ error: "Missing Authorization header" }, 401);
    }

    // Look up instance by webhook secret
    const instance = await ctx.runQuery(internal.instances.getByWebhookSecret, {
      webhookSecret: providedSecret,
    });
    if (!instance) {
      logger.warn("webhook: unauthorized - no instance found for provided secret");
      return corsJson({ error: "Unauthorized" }, 401);
    }

    // Envelope shape is @woofx3/api/webhooks CallbackEnvelope; `data` is the
    // discriminated CallbackEvent union. We trust the engine's contract and
    // narrow by event.type — anything outside the union falls through to
    // `handled: false` so legacy or future event types are safe to ignore.
    //
    // Escape $‑prefixed keys before dispatching — the engine embeds `$ref`
    // inside workflow definitions and Convex rejects reserved field names.
    const envelope = payload as CallbackEnvelope;
    const event = escapeDollarKeys(envelope.data) as CallbackEvent;
    const eventType: string = event?.type ?? (payload.type as string | undefined) ?? "";

    logger.info("webhook: event received", {
      instanceId: instance._id,
      type: eventType,
      payload: JSON.stringify(payload),
    });

    await ctx.runMutation(internal.engineEventLog.record, {
      instanceId: instance._id,
      eventType,
      payload: JSON.stringify(envelope.data ?? null),
      envelopeId: typeof envelope.id === "string" ? envelope.id : undefined,
      engineEventTime: typeof envelope.time === "string" ? envelope.time : undefined,
    });

    if (!event || typeof event !== "object" || !event.type) {
      logger.warn("webhook: envelope missing typed data", {
        eventType,
        hasData: !!payload.data,
      });
      return corsJson({ success: true, type: eventType, handled: false });
    }

    // Handled ahead of the switch because the engine types this repo builds
    // against may predate SESSION_SUMMARY, so it cannot be a case of the
    // CallbackEvent union. The body is validated field by field instead.
    if (eventType === SESSION_SUMMARY_EVENT_TYPE) {
      const result = await ctx.runMutation(internal.streamSessionSummaries.upsertFromWebhook, {
        instanceId: instance._id,
        data: event,
      });
      if (result.outcome === "invalid") {
        logger.warn("webhook: rejected session summary", { instanceId: instance._id, reason: result.reason });
        return corsJson({ error: `Invalid session summary: ${result.reason}` }, 400);
      }
      return corsJson({ success: true, type: eventType, outcome: result.outcome });
    }

    // Also ahead of the switch, for the same reason as SESSION_SUMMARY.
    if (eventType === WORKFLOW_HEALTH_CHANGED_EVENT_TYPE || eventType === WORKFLOW_HEALTH_SNAPSHOT_EVENT_TYPE) {
      const result =
        eventType === WORKFLOW_HEALTH_CHANGED_EVENT_TYPE
          ? await ctx.runMutation(internal.workflowHealth.recordChangedFromWebhook, {
              instanceId: instance._id,
              data: event,
            })
          : await ctx.runMutation(internal.workflowHealth.recordSnapshotFromWebhook, {
              instanceId: instance._id,
              data: event,
            });
      if (result.outcome === "invalid") {
        logger.warn("webhook: rejected workflow health", { instanceId: instance._id, reason: result.reason });
        return corsJson({ error: `Invalid workflow health: ${result.reason}` }, 400);
      }
      return corsJson({ success: true, type: eventType, outcome: result.outcome });
    }

    switch (event.type) {
      case EngineEventType.MODULE_INSTALLED: {
        const moduleDbId = await ctx.runMutation(internal.moduleWebhook.processModuleInstalled, {
          instanceId: instance._id,
          correlationKey: event.moduleKey,
          moduleName: event.moduleName,
          moduleVersion: event.version,
          // module.installed carries no definitions — those arrive on
          // separate module.trigger.registered / module.action.registered
          // events.
          triggers: [],
          actions: [],
        });
        // Neither install path (marketplace or direct zip upload) reliably has
        // the manifest in hand at this point, so fetch the engine's
        // authoritative copy out-of-band rather than block the webhook response.
        await ctx.scheduler.runAfter(0, internal.moduleManifestSync.syncManifest, {
          instanceId: instance._id,
          moduleDbId,
          manifestModuleId: event.moduleKey.split(":")[0],
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_INSTALL_FAILED: {
        await ctx.runMutation(internal.moduleWebhook.processModuleInstallFailed, {
          instanceId: instance._id,
          correlationKey: event.moduleKey,
          moduleName: event.moduleName,
          moduleVersion: event.version,
          statusMessage: event.error || "Module installation failed on the engine.",
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_DELETED: {
        await ctx.runMutation(internal.moduleWebhook.processModuleDeleted, {
          instanceId: instance._id,
          correlationKey: event.moduleKey,
          moduleName: event.moduleName,
          moduleVersion: undefined,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_DELETE_FAILED: {
        await ctx.runMutation(internal.moduleWebhook.processModuleDeleteFailed, {
          instanceId: instance._id,
          correlationKey: event.moduleKey,
          moduleName: event.moduleName,
          moduleVersion: undefined,
          error: event.error || undefined,
          conflicts: event.inUseResources,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_TRIGGER_REGISTERED: {
        await ctx.runMutation(internal.moduleWebhook.processRegisteredDefinitions, {
          instanceId: instance._id,
          moduleName: event.moduleName,
          moduleVersion: event.version,
          triggers: event.triggers,
          actions: [],
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_ACTION_REGISTERED: {
        await ctx.runMutation(internal.moduleWebhook.processRegisteredDefinitions, {
          instanceId: instance._id,
          moduleName: event.moduleName,
          moduleVersion: event.version,
          triggers: [],
          actions: event.actions,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_WIDGET_REGISTERED: {
        // Upsert the widget definition AND place it for this instance
        // (instanceWidgets join). Built-ins (createdByType "SYSTEM") have no
        // module — registerFromWebhook resolves moduleId only for MODULE widgets.
        // Key on the canonical projectionKey, NOT widget.id (the engine omits id
        // for built-ins, which previously produced a duplicate empty-id row).
        for (const widget of event.widgets) {
          // The engine sends ConfigField[] — the same shape a trigger's or
          // action's fields use — so there is nothing left to translate.
          const settings = widget.settings;
          const widgetId = widgetCanonicalKey({
            projectionKey: widget.projectionKey,
            createdByRef: widget.createdByRef,
            manifestId: widget.manifestId,
            canonicalId: widget.canonicalId,
            id: widget.id,
          });
          await ctx.runMutation(internal.moduleWidgets.registerFromWebhook, {
            instanceId: instance._id,
            widgetId,
            name: widget.name ?? widgetId,
            directory: widget.directory ?? "",
            description: widget.description,
            createdByType: widget.createdByType,
            createdByRef: widget.createdByRef,
            projectionKey: widget.projectionKey,
            alertTypes: widget.alertTypes ?? [],
            settings,
            surfaces: widget.surfaces,
            hostsSurface: widget.hostsSurface,
            taxonomy: widget.taxonomy,
          });
        }
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_WIDGET_DEREGISTERED: {
        for (const widget of event.widgets) {
          await ctx.runMutation(internal.moduleWidgets.unregister, {
            instanceId: instance._id,
            widgetId: widgetCanonicalKey({
              projectionKey: widget.projectionKey,
              createdByRef: widget.createdByRef,
              manifestId: widget.manifestId,
              canonicalId: widget.canonicalId,
              id: widget.id,
            }),
          });
        }
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.WORKFLOW_CREATED:
      case EngineEventType.WORKFLOW_UPDATED: {
        await ctx.runMutation(internal.workflowInternal.upsertFromWebhook, {
          instanceId: instance._id,
          engineWorkflowId: event.workflow.id,
          definition: event.workflow.definition,
          isEnabled: event.workflow.isEnabled,
        });
        if (event.correlationKey) {
          await ctx.runMutation(internal.workflowInternal.resolveCorrelation, {
            correlationKey: event.correlationKey,
            engineWorkflowId: event.workflow.id,
            op: event.type === EngineEventType.WORKFLOW_CREATED ? "create" : "update",
          });
        }
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.WORKFLOW_DELETED: {
        await ctx.runMutation(internal.workflowInternal.deleteFromWebhook, {
          instanceId: instance._id,
          engineWorkflowId: event.workflowId,
        });
        if (event.correlationKey) {
          await ctx.runMutation(internal.workflowInternal.resolveCorrelationForDelete, {
            correlationKey: event.correlationKey,
            engineWorkflowId: event.workflowId,
          });
        }
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.SCENE_CREATED: {
        await ctx.runMutation(internal.scenes.upsertFromWebhook, {
          instanceId: instance._id,
          engineSceneId: event.scene.id,
          name: event.scene.name,
          description: event.scene.description,
          widgetsJson: event.scene.widgetsJson,
          layoutJson: event.scene.layoutJson,
          createdByType: event.scene.createdByType,
          createdByRef: event.scene.createdByRef,
          createdAt: event.scene.createdAt,
          updatedAt: event.scene.updatedAt,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.SCENE_UPDATED: {
        await ctx.runMutation(internal.scenes.upsertFromWebhook, {
          instanceId: instance._id,
          engineSceneId: event.scene.id,
          name: event.scene.name,
          description: event.scene.description,
          widgetsJson: event.scene.widgetsJson,
          layoutJson: event.scene.layoutJson,
          createdByType: event.scene.createdByType,
          createdByRef: event.scene.createdByRef,
          createdAt: event.scene.createdAt,
          updatedAt: event.scene.updatedAt,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.SCENE_DELETED: {
        await ctx.runMutation(internal.scenes.deleteFromWebhook, {
          instanceId: instance._id,
          engineSceneId: event.sceneId,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.COMMAND_CREATED:
      case EngineEventType.COMMAND_UPDATED: {
        await ctx.runMutation(internal.chatCommands.upsertFromWebhook, {
          instanceId: instance._id,
          engineCommandId: event.command.id,
          command: event.command.command,
          // Already `$`-escaped: the whole webhook payload is escaped on the
          // way in (see the escapeDollarKeys call on the envelope above).
          actions: event.command.actions ?? [],
          cooldown: event.command.cooldown,
          priority: event.command.priority,
          enabled: event.command.enabled,
          visibility: event.command.visibility,
          groupIds: event.command.groupIds ?? [],
          usernames: event.command.usernames ?? [],
          argumentPattern: event.command.argumentPattern ?? "",
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.COMMAND_DELETED: {
        await ctx.runMutation(internal.chatCommands.deleteFromWebhook, {
          instanceId: instance._id,
          engineCommandId: event.commandId,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.GROUP_CREATED:
      case EngineEventType.GROUP_UPDATED: {
        await ctx.runMutation(internal.chatCommandGroups.upsertFromWebhook, {
          instanceId: instance._id,
          engineGroupId: event.group.id,
          name: event.group.name,
          description: event.group.description,
          isBuiltIn: event.group.isBuiltIn,
          engineCreatedAt: event.group.createdAt,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.GROUP_DELETED: {
        await ctx.runMutation(internal.chatCommandGroups.deleteFromWebhook, {
          instanceId: instance._id,
          engineGroupId: event.groupId,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.GROUP_MEMBER_ADDED: {
        await ctx.runMutation(internal.chatCommandGroups.addMemberFromWebhook, {
          instanceId: instance._id,
          engineGroupId: event.groupId,
          username: event.username,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.GROUP_MEMBER_REMOVED: {
        await ctx.runMutation(internal.chatCommandGroups.removeMemberFromWebhook, {
          instanceId: instance._id,
          engineGroupId: event.groupId,
          username: event.username,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_TRIGGER_DEREGISTERED: {
        await ctx.runMutation(internal.moduleWebhook.processDeregisteredDefinitions, {
          instanceId: instance._id,
          triggers: event.triggers,
          actions: [],
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_ACTION_DEREGISTERED: {
        await ctx.runMutation(internal.moduleWebhook.processDeregisteredDefinitions, {
          instanceId: instance._id,
          triggers: [],
          actions: event.actions,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_FUNCTION_REGISTERED: {
        await ctx.runMutation(internal.moduleFunctions.upsertFromWebhook, {
          instanceId: instance._id,
          moduleKey: event.moduleKey,
          moduleName: event.moduleName,
          version: event.version,
          functions: event.functions,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_FUNCTION_DEREGISTERED: {
        await ctx.runMutation(internal.moduleFunctions.deleteFromWebhook, {
          instanceId: instance._id,
          functions: event.functions,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_ASSET_REGISTERED: {
        await ctx.runMutation(internal.moduleAssets.upsertFromWebhook, {
          instanceId: instance._id,
          moduleKey: event.moduleKey,
          moduleName: event.moduleName,
          version: event.version,
          assets: event.assets,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_ASSET_DEREGISTERED: {
        await ctx.runMutation(internal.moduleAssets.deleteFromWebhook, {
          instanceId: instance._id,
          moduleKey: event.moduleKey,
          moduleName: event.moduleName,
          version: event.version,
          assets: event.assets,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_RESOURCE_INSTANCE_UPDATED:
      case EngineEventType.MODULE_RESOURCE_INSTANCE_CREATED: {
        await ctx.runMutation(internal.moduleResourceInstances.upsertFromWebhook, {
          instanceId: instance._id,
          instance: event.instance,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_RESOURCE_INSTANCE_DELETED: {
        await ctx.runMutation(internal.moduleResourceInstances.deleteFromWebhook, {
          instanceId: instance._id,
          instance: event.instance,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.MODULE_STORAGE_CHANGED: {
        const canonicalId = canonicalIdForStorageKey(event.key);
        if (canonicalId) {
          await ctx.runMutation(internal.resourceValues.upsert, {
            instanceId: instance._id,
            canonicalId,
            value: event.value ?? null,
          });
        }
        await ctx.runMutation(internal.transientEvents.emit, {
          instanceId: instance._id,
          correlationKey: `${event.moduleId}:${event.key}`,
          type: "module.storage.changed",
          status: "success",
          data: {
            moduleId: event.moduleId,
            key: event.key,
            value: event.value,
            previousValue: event.previousValue,
            occurredAt: event.occurredAt,
          },
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.ENGINE_RESPONSE_RECEIVED: {
        await ctx.runMutation(internal.transientEvents.emit, {
          instanceId: instance._id,
          correlationKey: event.correlationKey,
          type: "engine.response",
          status: event.status,
          message: event.error,
          data: event.data,
        });
        return corsJson({ success: true, type: event.type });
      }

      // A workflow run somebody is waiting on. transientEvents is keyed by the
      // client-generated id the trigger carried, so the UI subscribes before
      // the run exists; these three arms are the only thing that turns "the
      // event was published" into an outcome it can actually show.
      case EngineEventType.WORKFLOW_RUN_STARTED:
      case EngineEventType.WORKFLOW_RUN_COMPLETED:
      case EngineEventType.WORKFLOW_RUN_FAILED: {
        if (!event.triggerId) {
          // The api-side relay already drops these, so arriving here means an
          // older engine or a hand-published event. There is nothing to
          // correlate it to, and writing a row under an undefined key would
          // put it somewhere no subscriber looks.
          return corsJson({ success: true, type: event.type, handled: false });
        }
        await ctx.runMutation(internal.transientEvents.emit, {
          instanceId: instance._id,
          correlationKey: event.triggerId,
          type: event.type,
          status:
            event.type === EngineEventType.WORKFLOW_RUN_FAILED
              ? "error"
              : event.type === EngineEventType.WORKFLOW_RUN_COMPLETED
                ? "success"
                : "progress",
          message: event.type === EngineEventType.WORKFLOW_RUN_FAILED ? event.error : undefined,
          data: {
            workflowId: event.workflowId,
            executionId: event.executionId,
            triggeredBy: event.triggeredBy,
            occurredAt: event.occurredAt,
          },
        });
        return corsJson({ success: true, type: event.type });
      }

      // Durable run history. Separate from the WORKFLOW_RUN_STARTED family
      // above, which writes transientEvents for a caller watching one run:
      // these are database rows, and they outlive the person who wasn't there.
      case EngineEventType.WORKFLOW_RUN_RECORDED: {
        await ctx.runMutation(internal.workflowRuns.recordFromWebhook, {
          instanceId: instance._id,
          run: event.run,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.WORKFLOW_RUN_UPDATED: {
        await ctx.runMutation(internal.workflowRuns.updateFromWebhook, {
          instanceId: instance._id,
          run: event.run,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.WORKFLOW_RUN_STEP_RECORDED: {
        await ctx.runMutation(internal.workflowRuns.recordStepFromWebhook, {
          instanceId: instance._id,
          step: event.step,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.ALERT_RECORDED: {
        await ctx.runMutation(internal.engineAlerts.recordFromWebhook, {
          instanceId: instance._id,
          snapshot: event.alert,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.ALERT_REPLAYED:
      case EngineEventType.ALERT_COMPLETED:
      case EngineEventType.ALERT_FAILED:
      case EngineEventType.ALERT_TIMED_OUT:
      case EngineEventType.ALERT_SKIPPED: {
        await ctx.runMutation(internal.engineAlerts.updateFromWebhook, {
          instanceId: instance._id,
          snapshot: event.alert,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.WIDGET_STATUS_CHANGED: {
        const correlationKey = event.widgetCanonicalId ?? `${event.moduleId}:${event.instanceId}:${event.key}`;
        await ctx.runMutation(internal.transientEvents.emit, {
          instanceId: instance._id,
          correlationKey,
          type: "widget.status.changed",
          status: "success",
          data: {
            moduleId: event.moduleId,
            widgetInstanceId: event.instanceId,
            widgetCanonicalId: event.widgetCanonicalId,
            key: event.key,
            value: event.value,
            occurredAt: event.occurredAt,
          },
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.OVERLAY_TOKEN_REVOKED: {
        // Best-effort cache invalidation — see clearOverlayUrlByTokenId's doc
        // comment. woofx3-ui's own revoke/rotate calls (convex/browserSource.ts)
        // already keep their own cache correct; this only matters when a
        // token is revoked through some other channel.
        await ctx.runMutation(internal.browserSource.clearOverlayUrlByTokenId, {
          engineTokenId: event.tokenId,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.STREAM_ONLINE: {
        await ctx.runMutation(internal.instanceLiveState.onStreamOnline, {
          instanceId: instance._id,
          twitchUserId: event.twitchUserId,
          startedAt: event.startedAt,
          streamTitle: event.streamTitle,
          gameName: event.gameName,
          viewerCount: event.viewerCount,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.STREAM_OFFLINE: {
        await ctx.runMutation(internal.instanceLiveState.onStreamOffline, {
          instanceId: instance._id,
          twitchUserId: event.twitchUserId,
        });
        return corsJson({ success: true, type: event.type });
      }

      case EngineEventType.SESSION_STARTED: {
        await ctx.runMutation(internal.instanceLiveState.onSessionStarted, {
          instanceId: instance._id,
          sessionId: event.sessionId,
          sessionStartedAt: event.startedAt,
        });
        return corsJson({ success: true, type: event.type });
      }

      default: {
        logger.warn("webhook: unhandled event type", { eventType });
        return corsJson({ success: true, type: eventType, handled: false });
      }
    }
  }),
});

/**
 * Progress callbacks from the woofx3 maintenance API while it provisions or
 * tears down a managed engine.
 *
 * Unlike the engine's own webhook above, this caller is one trusted service
 * rather than one engine per tenant, so it authenticates with an HMAC over the
 * exact body instead of a per-instance bearer token: there is no instance to
 * look a token up by until provisioning finishes. The engine a callback is
 * about is found by `engineId`, which this deployment recorded when it asked
 * for the engine.
 *
 * Delivery is at-least-once and the sender retries until it sees a 2xx, so a
 * repeat must be acknowledged rather than applied twice, and a rejected
 * signature must answer 401 rather than 200.
 */
http.route({
  path: "/api/webhooks/maintenance",
  method: "POST",
  handler: httpAction(async (ctx, request) => {
    const secret = process.env.MAINTENANCE_WEBHOOK_SECRET;
    if (!secret) {
      logger.error("maintenance webhook: MAINTENANCE_WEBHOOK_SECRET is not configured");
      return new Response(JSON.stringify({ error: "Not configured" }), {
        status: 503,
        headers: { "Content-Type": "application/json" },
      });
    }

    // The signature covers the exact bytes sent, so the body is read as text
    // and parsed only after it verifies.
    const body = await request.text();
    const verification = await verifySignature(body, request.headers.get(SIGNATURE_HEADER), secret, new Date());
    if (!verification.valid) {
      logger.warn("maintenance webhook: rejected", { reason: verification.reason });
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { "Content-Type": "application/json" },
      });
    }

    let payload: unknown;
    try {
      payload = JSON.parse(body);
    } catch {
      return corsJson({ error: "Invalid JSON" }, 400);
    }
    const event = payload as Record<string, unknown>;
    const eventId = typeof event.id === "string" ? event.id : null;
    const eventType = typeof event.type === "string" ? event.type : null;
    if (!eventId || !eventType) {
      return corsJson({ error: "Missing id or type" }, 400);
    }
    const engineId = typeof event.engineId === "string" ? event.engineId : null;
    if (!engineId) {
      logger.warn("maintenance webhook: event without an engineId", { type: eventType, eventId });
      return corsJson({ success: true, type: eventType, handled: false });
    }

    logger.info("maintenance webhook: event received", { type: eventType, engineId, eventId });

    // Deduping and applying are one transaction, so a redelivery of an event
    // whose effect did not commit is applied rather than swallowed.
    const result = await ctx.runMutation(internal.provisioningInternal.applyCallbackEvent, {
      eventId,
      eventType,
      maintenanceEngineId: engineId,
      step: typeof event.step === "string" ? event.step : undefined,
      label: typeof event.label === "string" ? event.label : undefined,
      stepStatus: maintenanceStepStatus(event.status) ?? undefined,
      url: typeof event.url === "string" ? event.url : undefined,
      version: typeof event.version === "string" ? event.version : undefined,
      runKind: maintenanceRunKind(event.runKind) ?? undefined,
      error: maintenanceErrorText(event.error),
    });
    return corsJson({ success: true, type: eventType, ...result });
  }),
});

/** Which kind of run an event came from; a failure means opposite things for a build and a teardown. */
function maintenanceRunKind(value: unknown): "provision" | "deprovision" | "redeploy" | null {
  switch (value) {
    case "provision":
    case "deprovision":
    case "redeploy":
      return value;
    default:
      return null;
  }
}

/** The maintenance API's step statuses; anything else means the contract moved and the event is refused. */
function maintenanceStepStatus(value: unknown): "pending" | "running" | "succeeded" | "failed" | "skipped" | null {
  switch (value) {
    case "pending":
    case "running":
    case "succeeded":
    case "failed":
    case "skipped":
      return value;
    default:
      return null;
  }
}

/** `{ code, message }` flattened for display; the code is kept because it is stable and the message is not. */
function maintenanceErrorText(value: unknown): string | undefined {
  if (!value || typeof value !== "object") {
    return undefined;
  }
  const error = value as { code?: unknown; message?: unknown };
  if (typeof error.message !== "string") {
    return undefined;
  }
  return typeof error.code === "string" ? `${error.code}: ${error.message}` : error.message;
}

http.route({
  pathPrefix: "/browser-source/",
  method: "GET",
  handler: httpAction(async (ctx, request) => {
    const url = new URL(request.url);
    const segments = url.pathname.split("/").filter(Boolean);
    const key = segments[1];

    if (!key) {
      return new Response("Missing source key", { status: 400 });
    }

    const sourceKey = await ctx.runQuery(internal.browserSource.getSourceKeyByKey, { key });
    if (!sourceKey) {
      return new Response("Invalid source key", { status: 404 });
    }

    await ctx.runMutation(internal.browserSource.updateSourceKeyLastUsed, {
      keyId: sourceKey._id,
      lastUsedAt: Date.now(),
    });

    const scene = await ctx.runQuery(internal.browserSource.getScene, { sceneId: sourceKey.sceneId });
    if (!scene) {
      return new Response("Scene not found", { status: 404 });
    }

    const sceneName = scene.name ?? "Scene";
    const htmlResponse = (body: string) =>
      new Response(body, { status: 200, headers: { "Content-Type": "text/html; charset=utf-8" } });

    // Scenes are engine-authoritative and the engine renders the overlay, so this
    // route just redirects to the engine-minted overlay-token URL cached on the
    // source key (see convex/browserSource.ts's getOrCreateBrowserSourceKey — it
    // mints via the engine's overlayTokenRoutes at key-creation time, not here, so
    // this stays a single fast lookup on every OBS page load). Why a redirect
    // rather than a wrapper page: see buildBrowserSourceRedirect.
    if (!scene.engineSceneId) {
      return htmlResponse(
        buildBrowserSourcePlaceholderHtml({
          sceneName,
          reason: "This scene has not finished syncing with the engine yet.",
        })
      );
    }

    // A URL from before Scene Manager replaced streamware's overlay path resolves to nothing;
    // say so rather than redirecting to a dead page. Reopening the scene editor re-mints it.
    if (!isCurrentSceneUrl(sourceKey.overlayUrl, scene.engineSceneId)) {
      return htmlResponse(
        buildBrowserSourcePlaceholderHtml({
          sceneName,
          reason: "This browser source hasn't finished setting up yet — reopen it from the scene editor.",
        })
      );
    }

    return buildBrowserSourceRedirect(sourceKey.overlayUrl);
  }),
});

/** How long the control plane waits for the engine to run a webhook handler. */
const INBOUND_WEBHOOK_ENGINE_TIMEOUT_MS = 10_000;

// Third-party webhooks: a POST, or a GET verification handshake, to
// /api/webhooks/<endpointId>. The exact /api/webhooks/woofx3 routes above
// still win: the router matches exact paths before prefixes.
const inboundWebhookHandler = httpAction(async (ctx, request) => {
  const url = new URL(request.url);
  const path = parseInboundWebhookPath(url.pathname);
  if (!path.ok) {
    return new Response(null, { status: 404 });
  }
  const endpoint = await ctx.runQuery(internal.inboundWebhooks.getByEndpointId, { endpointId: path.endpointId });
  if (!endpoint || !endpoint.isEnabled) {
    return new Response(null, { status: 404 });
  }

  if (Number(request.headers.get("content-length") ?? "0") > MAX_INBOUND_BODY_BYTES) {
    return new Response(null, { status: 413 });
  }
  const body = await request.arrayBuffer();
  if (body.byteLength > MAX_INBOUND_BODY_BYTES) {
    return new Response(null, { status: 413 });
  }

  // Bookkeeping must never change the answer a provider gets.
  const recordDelivery = async (status: number, error?: string) => {
    try {
      await ctx.runMutation(internal.inboundWebhooks.recordDelivery, { endpointId: endpoint._id, status, error });
    } catch (err) {
      logger.warn("inbound webhook: failed to record delivery", {
        endpointId: endpoint.endpointId,
        error: String(err),
      });
    }
  };

  const instance = await ctx.runQuery(internal.instances.getInternal, { instanceId: endpoint.instanceId });
  if (!instance?.url || !instance.clientId || !instance.clientSecret) {
    await recordDelivery(503, "instance is not registered with an engine");
    return new Response(null, { status: 503 });
  }

  const forwarded = buildForwardedRequest(request, url, body, crypto.randomUUID());
  let engineResponse: InboundWebhookResponse;
  try {
    const rpc = createEngineRpcSession<EngineApi>(instance.url, instance.clientId, instance.clientSecret);
    engineResponse = await withEngineTimeout(
      rpc.handleInboundWebhook(endpoint.triggerKey, forwarded),
      INBOUND_WEBHOOK_ENGINE_TIMEOUT_MS
    );
  } catch (err) {
    const timedOut = err instanceof EngineTimeoutError;
    const status = timedOut ? 504 : 503;
    await recordDelivery(status, timedOut ? "engine did not answer in time" : "engine unreachable");
    return new Response(null, { status });
  }

  const response = toHttpResponse(engineResponse);
  await recordDelivery(
    response.status,
    response.status >= 500 ? `engine answered ${engineResponse.status}` : undefined
  );
  return response;
});

http.route({ pathPrefix: "/api/webhooks/", method: "POST", handler: inboundWebhookHandler });
http.route({ pathPrefix: "/api/webhooks/", method: "GET", handler: inboundWebhookHandler });

/** How long a remote macro trigger waits for the engine to accept the run. */
const MACRO_TRIGGER_ENGINE_TIMEOUT_MS = 10_000;

/** Provenance for runs fired by a trigger URL. Unlike "dashboard", these are recorded in the run history. */
const MACRO_TRIGGER_PROVENANCE = "macro-trigger";

function macroTriggerJson(
  status: number,
  body: Record<string, unknown>,
  headers: Record<string, string> = {}
): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", "Cache-Control": "no-store", ...headers },
  });
}

// A macro's remote trigger: POST /api/macros/trigger/<token>, or POST
// /api/macros/trigger with `Authorization: Bearer <token>`. GET only for a
// trigger that opted in. Requests from a web page are refused before the token
// is looked at, and a malformed token and an unknown one get the same 404.
const macroTriggerHandler = httpAction(async (ctx, request) => {
  const refuse = (refusal: Parameters<typeof triggerRefusalResponse>[0]) => {
    const response = triggerRefusalResponse(refusal);
    return macroTriggerJson(response.status, response.body, response.headers);
  };

  if (isBrowserRequest(request.headers.get("origin"))) {
    return refuse({ outcome: "browser-origin" });
  }
  const url = new URL(request.url);
  const token = resolveTriggerToken(url.pathname, request.headers.get("authorization"));
  if (!token) {
    return refuse({ outcome: "not-found" });
  }
  const method = request.method === "GET" ? "GET" : "POST";

  if (Number(request.headers.get("content-length") ?? "0") > MAX_TRIGGER_BODY_BYTES) {
    return macroTriggerJson(413, { ok: false, error: "body too large" });
  }
  const bodyBytes = method === "POST" ? await request.arrayBuffer() : new ArrayBuffer(0);
  if (bodyBytes.byteLength > MAX_TRIGGER_BODY_BYTES) {
    return macroTriggerJson(413, { ok: false, error: "body too large" });
  }
  const parsed = parseTriggerValues({
    contentType: request.headers.get("content-type"),
    body: new TextDecoder().decode(bodyBytes),
    query: url.searchParams,
  });
  if (!parsed.ok) {
    return macroTriggerJson(400, { ok: false, error: parsed.error });
  }

  const claim = await ctx.runMutation(internal.macroTriggers.claim, {
    tokenHash: await hashTriggerToken(token),
    method,
    values: valuesToPairs(parsed.values),
  });
  if (claim.outcome !== "run") {
    return refuse(claim);
  }

  // Bookkeeping must never change the answer the device gets.
  const recordOutcome = async (failure?: string) => {
    try {
      await ctx.runMutation(internal.macroTriggers.recordOutcome, { triggerId: claim.triggerId, failure });
    } catch (err) {
      logger.warn("macro trigger: failed to record outcome", { error: String(err) });
    }
  };

  try {
    const result = await withEngineTimeout(
      executeMacroPlan(claim.engine, claim.plan, MACRO_TRIGGER_PROVENANCE),
      MACRO_TRIGGER_ENGINE_TIMEOUT_MS
    );
    await recordOutcome();
    return macroTriggerJson(202, { ok: true, ...(result.triggerId ? { triggerId: result.triggerId } : {}) });
  } catch (err) {
    if (err instanceof MacroRunRefused) {
      await recordOutcome(err.message);
      return macroTriggerJson(409, { ok: false, error: err.message });
    }
    const timedOut = err instanceof EngineTimeoutError;
    // A transport failure's text can carry internals (hosts, stack traces);
    // the caller only learns that the engine did not take the run.
    logger.warn("macro trigger: engine call failed", { error: String(err), timedOut });
    const error = timedOut ? "the engine did not answer in time" : "the engine did not accept the run";
    await recordOutcome(error);
    return macroTriggerJson(timedOut ? 504 : 502, { ok: false, error });
  }
});

http.route({ path: MACRO_TRIGGER_PATH, method: "POST", handler: macroTriggerHandler });
http.route({ path: MACRO_TRIGGER_PATH, method: "GET", handler: macroTriggerHandler });
http.route({ pathPrefix: MACRO_TRIGGER_PATH_PREFIX, method: "POST", handler: macroTriggerHandler });
http.route({ pathPrefix: MACRO_TRIGGER_PATH_PREFIX, method: "GET", handler: macroTriggerHandler });

export default http;
