/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as accountMembers from "../accountMembers.js";
import type * as accounts from "../accounts.js";
import type * as actionDefinitions from "../actionDefinitions.js";
import type * as activityPanel from "../activityPanel.js";
import type * as adBreaks from "../adBreaks.js";
import type * as alertActions from "../alertActions.js";
import type * as alertLog from "../alertLog.js";
import type * as auth from "../auth.js";
import type * as browserSource from "../browserSource.js";
import type * as chatCommandActions from "../chatCommandActions.js";
import type * as chatCommandGroups from "../chatCommandGroups.js";
import type * as chatCommands from "../chatCommands.js";
import type * as configBackup from "../configBackup.js";
import type * as crons from "../crons.js";
import type * as dashboardCounters from "../dashboardCounters.js";
import type * as dashboardLayouts from "../dashboardLayouts.js";
import type * as dashboardNotes from "../dashboardNotes.js";
import type * as debug from "../debug.js";
import type * as engineAlerts from "../engineAlerts.js";
import type * as engineCapabilities from "../engineCapabilities.js";
import type * as engineEventLog from "../engineEventLog.js";
import type * as engineHealth from "../engineHealth.js";
import type * as engineInfo from "../engineInfo.js";
import type * as engineSync from "../engineSync.js";
import type * as engineSyncInternal from "../engineSyncInternal.js";
import type * as fieldOptions from "../fieldOptions.js";
import type * as gettingStarted from "../gettingStarted.js";
import type * as goLive from "../goLive.js";
import type * as http from "../http.js";
import type * as inboundWebhooks from "../inboundWebhooks.js";
import type * as instanceLiveState from "../instanceLiveState.js";
import type * as instances from "../instances.js";
import type * as integrationCredentials from "../integrationCredentials.js";
import type * as invitations from "../invitations.js";
import type * as lib_adBreaks from "../lib/adBreaks.js";
import type * as lib_alertQueueResults from "../lib/alertQueueResults.js";
import type * as lib_alertWidgets from "../lib/alertWidgets.js";
import type * as lib_browserSourceHtml from "../lib/browserSourceHtml.js";
import type * as lib_canonicalRef from "../lib/canonicalRef.js";
import type * as lib_completionPolling from "../lib/completionPolling.js";
import type * as lib_configBundle from "../lib/configBundle.js";
import type * as lib_definitionCatalog from "../lib/definitionCatalog.js";
import type * as lib_dollarKeys from "../lib/dollarKeys.js";
import type * as lib_engineCapabilities from "../lib/engineCapabilities.js";
import type * as lib_engineInstanceUrl from "../lib/engineInstanceUrl.js";
import type * as lib_engineObsStatus from "../lib/engineObsStatus.js";
import type * as lib_engineSync_config from "../lib/engineSync/config.js";
import type * as lib_engineSync_steps from "../lib/engineSync/steps.js";
import type * as lib_engineSync_steps_actions from "../lib/engineSync/steps/actions.js";
import type * as lib_engineSync_steps_commands from "../lib/engineSync/steps/commands.js";
import type * as lib_engineSync_steps_functions from "../lib/engineSync/steps/functions.js";
import type * as lib_engineSync_steps_groups from "../lib/engineSync/steps/groups.js";
import type * as lib_engineSync_steps_modules from "../lib/engineSync/steps/modules.js";
import type * as lib_engineSync_steps_resources from "../lib/engineSync/steps/resources.js";
import type * as lib_engineSync_steps_scenes from "../lib/engineSync/steps/scenes.js";
import type * as lib_engineSync_steps_triggers from "../lib/engineSync/steps/triggers.js";
import type * as lib_engineSync_steps_widgets from "../lib/engineSync/steps/widgets.js";
import type * as lib_engineSync_steps_workflows from "../lib/engineSync/steps/workflows.js";
import type * as lib_engineSync_syncRow from "../lib/engineSync/syncRow.js";
import type * as lib_engineTestRun from "../lib/engineTestRun.js";
import type * as lib_fieldOptions from "../lib/fieldOptions.js";
import type * as lib_gettingStarted from "../lib/gettingStarted.js";
import type * as lib_goLiveFacts from "../lib/goLiveFacts.js";
import type * as lib_goLiveMarker from "../lib/goLiveMarker.js";
import type * as lib_inboundWebhookDelivery from "../lib/inboundWebhookDelivery.js";
import type * as lib_inboundWebhookPath from "../lib/inboundWebhookPath.js";
import type * as lib_inboundWebhookRelay from "../lib/inboundWebhookRelay.js";
import type * as lib_instanceAccess from "../lib/instanceAccess.js";
import type * as lib_instanceRoles from "../lib/instanceRoles.js";
import type * as lib_instanceTeardown from "../lib/instanceTeardown.js";
import type * as lib_integrationClientId from "../lib/integrationClientId.js";
import type * as lib_invitationTarget from "../lib/invitationTarget.js";
import type * as lib_macroExecution from "../lib/macroExecution.js";
import type * as lib_macroTrigger from "../lib/macroTrigger.js";
import type * as lib_macroVariables from "../lib/macroVariables.js";
import type * as lib_maintenanceClient from "../lib/maintenanceClient.js";
import type * as lib_maintenanceSignature from "../lib/maintenanceSignature.js";
import type * as lib_maintenanceUpgrade from "../lib/maintenanceUpgrade.js";
import type * as lib_manualRunOrigin from "../lib/manualRunOrigin.js";
import type * as lib_marketplaceImages from "../lib/marketplaceImages.js";
import type * as lib_moderation from "../lib/moderation.js";
import type * as lib_moduleDisplayName from "../lib/moduleDisplayName.js";
import type * as lib_moduleKey from "../lib/moduleKey.js";
import type * as lib_moduleOAuth from "../lib/moduleOAuth.js";
import type * as lib_modulePermissions from "../lib/modulePermissions.js";
import type * as lib_moduleSettingsVisibility from "../lib/moduleSettingsVisibility.js";
import type * as lib_oauthCallback from "../lib/oauthCallback.js";
import type * as lib_oauthErrors from "../lib/oauthErrors.js";
import type * as lib_oauthHandoff from "../lib/oauthHandoff.js";
import type * as lib_oauthState from "../lib/oauthState.js";
import type * as lib_pinStrategy from "../lib/pinStrategy.js";
import type * as lib_pkce from "../lib/pkce.js";
import type * as lib_previewEngine from "../lib/previewEngine.js";
import type * as lib_recapClips from "../lib/recapClips.js";
import type * as lib_resourceKinds from "../lib/resourceKinds.js";
import type * as lib_runTriggerEvent from "../lib/runTriggerEvent.js";
import type * as lib_safeRedirect from "../lib/safeRedirect.js";
import type * as lib_sceneCascade from "../lib/sceneCascade.js";
import type * as lib_sceneOverlayUrl from "../lib/sceneOverlayUrl.js";
import type * as lib_sceneSerialization from "../lib/sceneSerialization.js";
import type * as lib_sessionSummary from "../lib/sessionSummary.js";
import type * as lib_setupApply from "../lib/setupApply.js";
import type * as lib_setupInterests from "../lib/setupInterests.js";
import type * as lib_setupPlatforms from "../lib/setupPlatforms.js";
import type * as lib_shoutoutSchedule from "../lib/shoutoutSchedule.js";
import type * as lib_spotifyIntegrationScopes from "../lib/spotifyIntegrationScopes.js";
import type * as lib_starterPackLedger from "../lib/starterPackLedger.js";
import type * as lib_starterPacks from "../lib/starterPacks.js";
import type * as lib_streamInfo from "../lib/streamInfo.js";
import type * as lib_streamRecap from "../lib/streamRecap.js";
import type * as lib_supporters from "../lib/supporters.js";
import type * as lib_teamAccess from "../lib/teamAccess.js";
import type * as lib_twitchAuth from "../lib/twitchAuth.js";
import type * as lib_twitchChannels from "../lib/twitchChannels.js";
import type * as lib_twitchChat from "../lib/twitchChat.js";
import type * as lib_twitchIntegrationScopes from "../lib/twitchIntegrationScopes.js";
import type * as lib_twitchLinkPolicy from "../lib/twitchLinkPolicy.js";
import type * as lib_twitchRefresh from "../lib/twitchRefresh.js";
import type * as lib_twitchScopeHealth from "../lib/twitchScopeHealth.js";
import type * as lib_twitchTokenGrant from "../lib/twitchTokenGrant.js";
import type * as lib_twitchUsers from "../lib/twitchUsers.js";
import type * as lib_webhookEndpointKey from "../lib/webhookEndpointKey.js";
import type * as lib_widgetKey from "../lib/widgetKey.js";
import type * as lib_widgetThemes from "../lib/widgetThemes.js";
import type * as lib_workflowHealth from "../lib/workflowHealth.js";
import type * as logger from "../logger.js";
import type * as macroTriggers from "../macroTriggers.js";
import type * as macros from "../macros.js";
import type * as marketplace from "../marketplace.js";
import type * as migrations_backfillAccountMembers from "../migrations/backfillAccountMembers.js";
import type * as migrations_backfillCommandActions from "../migrations/backfillCommandActions.js";
import type * as migrations_backfillSharedMacros from "../migrations/backfillSharedMacros.js";
import type * as moderation from "../moderation.js";
import type * as moduleAssets from "../moduleAssets.js";
import type * as moduleDetail from "../moduleDetail.js";
import type * as moduleEngine from "../moduleEngine.js";
import type * as moduleFunctions from "../moduleFunctions.js";
import type * as moduleIntegrationState from "../moduleIntegrationState.js";
import type * as moduleManifestSync from "../moduleManifestSync.js";
import type * as moduleOAuth from "../moduleOAuth.js";
import type * as moduleRepository from "../moduleRepository.js";
import type * as moduleResourceActions from "../moduleResourceActions.js";
import type * as moduleResourceInstances from "../moduleResourceInstances.js";
import type * as moduleSettingsActions from "../moduleSettingsActions.js";
import type * as moduleWebhook from "../moduleWebhook.js";
import type * as moduleWidgets from "../moduleWidgets.js";
import type * as oauthConnectHandoff from "../oauthConnectHandoff.js";
import type * as obsStatus from "../obsStatus.js";
import type * as pageIntros from "../pageIntros.js";
import type * as pins from "../pins.js";
import type * as platformRealtime from "../platformRealtime.js";
import type * as previewEngine from "../previewEngine.js";
import type * as provisioning from "../provisioning.js";
import type * as provisioningInternal from "../provisioningInternal.js";
import type * as registration from "../registration.js";
import type * as resourceKinds from "../resourceKinds.js";
import type * as resourceValues from "../resourceValues.js";
import type * as resources from "../resources.js";
import type * as sceneActions from "../sceneActions.js";
import type * as sceneWidgets from "../sceneWidgets.js";
import type * as scenes from "../scenes.js";
import type * as seeds_triggerActions from "../seeds/triggerActions.js";
import type * as setup from "../setup.js";
import type * as setupApply from "../setupApply.js";
import type * as setupPlatforms from "../setupPlatforms.js";
import type * as setupPlatformsActions from "../setupPlatformsActions.js";
import type * as shoutouts from "../shoutouts.js";
import type * as spotifyConnect from "../spotifyConnect.js";
import type * as spotifyIntegration from "../spotifyIntegration.js";
import type * as starterPacks from "../starterPacks.js";
import type * as storage from "../storage.js";
import type * as streamInfo from "../streamInfo.js";
import type * as streamRecap from "../streamRecap.js";
import type * as streamSessionSummaries from "../streamSessionSummaries.js";
import type * as streamStatus from "../streamStatus.js";
import type * as supporters from "../supporters.js";
import type * as transientEvents from "../transientEvents.js";
import type * as triggerDefinitions from "../triggerDefinitions.js";
import type * as twitchAuth from "../twitchAuth.js";
import type * as twitchBroadcast from "../twitchBroadcast.js";
import type * as twitchClips from "../twitchClips.js";
import type * as twitchIntegration from "../twitchIntegration.js";
import type * as users from "../users.js";
import type * as webhookAuth from "../webhookAuth.js";
import type * as workflowActions from "../workflowActions.js";
import type * as workflowCatalog from "../workflowCatalog.js";
import type * as workflowCatalogContext from "../workflowCatalogContext.js";
import type * as workflowHealth from "../workflowHealth.js";
import type * as workflowInternal from "../workflowInternal.js";
import type * as workflowRuns from "../workflowRuns.js";
import type * as workflows from "../workflows.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  accountMembers: typeof accountMembers;
  accounts: typeof accounts;
  actionDefinitions: typeof actionDefinitions;
  activityPanel: typeof activityPanel;
  adBreaks: typeof adBreaks;
  alertActions: typeof alertActions;
  alertLog: typeof alertLog;
  auth: typeof auth;
  browserSource: typeof browserSource;
  chatCommandActions: typeof chatCommandActions;
  chatCommandGroups: typeof chatCommandGroups;
  chatCommands: typeof chatCommands;
  configBackup: typeof configBackup;
  crons: typeof crons;
  dashboardCounters: typeof dashboardCounters;
  dashboardLayouts: typeof dashboardLayouts;
  dashboardNotes: typeof dashboardNotes;
  debug: typeof debug;
  engineAlerts: typeof engineAlerts;
  engineCapabilities: typeof engineCapabilities;
  engineEventLog: typeof engineEventLog;
  engineHealth: typeof engineHealth;
  engineInfo: typeof engineInfo;
  engineSync: typeof engineSync;
  engineSyncInternal: typeof engineSyncInternal;
  fieldOptions: typeof fieldOptions;
  gettingStarted: typeof gettingStarted;
  goLive: typeof goLive;
  http: typeof http;
  inboundWebhooks: typeof inboundWebhooks;
  instanceLiveState: typeof instanceLiveState;
  instances: typeof instances;
  integrationCredentials: typeof integrationCredentials;
  invitations: typeof invitations;
  "lib/adBreaks": typeof lib_adBreaks;
  "lib/alertQueueResults": typeof lib_alertQueueResults;
  "lib/alertWidgets": typeof lib_alertWidgets;
  "lib/browserSourceHtml": typeof lib_browserSourceHtml;
  "lib/canonicalRef": typeof lib_canonicalRef;
  "lib/completionPolling": typeof lib_completionPolling;
  "lib/configBundle": typeof lib_configBundle;
  "lib/definitionCatalog": typeof lib_definitionCatalog;
  "lib/dollarKeys": typeof lib_dollarKeys;
  "lib/engineCapabilities": typeof lib_engineCapabilities;
  "lib/engineInstanceUrl": typeof lib_engineInstanceUrl;
  "lib/engineObsStatus": typeof lib_engineObsStatus;
  "lib/engineSync/config": typeof lib_engineSync_config;
  "lib/engineSync/steps": typeof lib_engineSync_steps;
  "lib/engineSync/steps/actions": typeof lib_engineSync_steps_actions;
  "lib/engineSync/steps/commands": typeof lib_engineSync_steps_commands;
  "lib/engineSync/steps/functions": typeof lib_engineSync_steps_functions;
  "lib/engineSync/steps/groups": typeof lib_engineSync_steps_groups;
  "lib/engineSync/steps/modules": typeof lib_engineSync_steps_modules;
  "lib/engineSync/steps/resources": typeof lib_engineSync_steps_resources;
  "lib/engineSync/steps/scenes": typeof lib_engineSync_steps_scenes;
  "lib/engineSync/steps/triggers": typeof lib_engineSync_steps_triggers;
  "lib/engineSync/steps/widgets": typeof lib_engineSync_steps_widgets;
  "lib/engineSync/steps/workflows": typeof lib_engineSync_steps_workflows;
  "lib/engineSync/syncRow": typeof lib_engineSync_syncRow;
  "lib/engineTestRun": typeof lib_engineTestRun;
  "lib/fieldOptions": typeof lib_fieldOptions;
  "lib/gettingStarted": typeof lib_gettingStarted;
  "lib/goLiveFacts": typeof lib_goLiveFacts;
  "lib/goLiveMarker": typeof lib_goLiveMarker;
  "lib/inboundWebhookDelivery": typeof lib_inboundWebhookDelivery;
  "lib/inboundWebhookPath": typeof lib_inboundWebhookPath;
  "lib/inboundWebhookRelay": typeof lib_inboundWebhookRelay;
  "lib/instanceAccess": typeof lib_instanceAccess;
  "lib/instanceRoles": typeof lib_instanceRoles;
  "lib/instanceTeardown": typeof lib_instanceTeardown;
  "lib/integrationClientId": typeof lib_integrationClientId;
  "lib/invitationTarget": typeof lib_invitationTarget;
  "lib/macroExecution": typeof lib_macroExecution;
  "lib/macroTrigger": typeof lib_macroTrigger;
  "lib/macroVariables": typeof lib_macroVariables;
  "lib/maintenanceClient": typeof lib_maintenanceClient;
  "lib/maintenanceSignature": typeof lib_maintenanceSignature;
  "lib/maintenanceUpgrade": typeof lib_maintenanceUpgrade;
  "lib/manualRunOrigin": typeof lib_manualRunOrigin;
  "lib/marketplaceImages": typeof lib_marketplaceImages;
  "lib/moderation": typeof lib_moderation;
  "lib/moduleDisplayName": typeof lib_moduleDisplayName;
  "lib/moduleKey": typeof lib_moduleKey;
  "lib/moduleOAuth": typeof lib_moduleOAuth;
  "lib/modulePermissions": typeof lib_modulePermissions;
  "lib/moduleSettingsVisibility": typeof lib_moduleSettingsVisibility;
  "lib/oauthCallback": typeof lib_oauthCallback;
  "lib/oauthErrors": typeof lib_oauthErrors;
  "lib/oauthHandoff": typeof lib_oauthHandoff;
  "lib/oauthState": typeof lib_oauthState;
  "lib/pinStrategy": typeof lib_pinStrategy;
  "lib/pkce": typeof lib_pkce;
  "lib/previewEngine": typeof lib_previewEngine;
  "lib/recapClips": typeof lib_recapClips;
  "lib/resourceKinds": typeof lib_resourceKinds;
  "lib/runTriggerEvent": typeof lib_runTriggerEvent;
  "lib/safeRedirect": typeof lib_safeRedirect;
  "lib/sceneCascade": typeof lib_sceneCascade;
  "lib/sceneOverlayUrl": typeof lib_sceneOverlayUrl;
  "lib/sceneSerialization": typeof lib_sceneSerialization;
  "lib/sessionSummary": typeof lib_sessionSummary;
  "lib/setupApply": typeof lib_setupApply;
  "lib/setupInterests": typeof lib_setupInterests;
  "lib/setupPlatforms": typeof lib_setupPlatforms;
  "lib/shoutoutSchedule": typeof lib_shoutoutSchedule;
  "lib/spotifyIntegrationScopes": typeof lib_spotifyIntegrationScopes;
  "lib/starterPackLedger": typeof lib_starterPackLedger;
  "lib/starterPacks": typeof lib_starterPacks;
  "lib/streamInfo": typeof lib_streamInfo;
  "lib/streamRecap": typeof lib_streamRecap;
  "lib/supporters": typeof lib_supporters;
  "lib/teamAccess": typeof lib_teamAccess;
  "lib/twitchAuth": typeof lib_twitchAuth;
  "lib/twitchChannels": typeof lib_twitchChannels;
  "lib/twitchChat": typeof lib_twitchChat;
  "lib/twitchIntegrationScopes": typeof lib_twitchIntegrationScopes;
  "lib/twitchLinkPolicy": typeof lib_twitchLinkPolicy;
  "lib/twitchRefresh": typeof lib_twitchRefresh;
  "lib/twitchScopeHealth": typeof lib_twitchScopeHealth;
  "lib/twitchTokenGrant": typeof lib_twitchTokenGrant;
  "lib/twitchUsers": typeof lib_twitchUsers;
  "lib/webhookEndpointKey": typeof lib_webhookEndpointKey;
  "lib/widgetKey": typeof lib_widgetKey;
  "lib/widgetThemes": typeof lib_widgetThemes;
  "lib/workflowHealth": typeof lib_workflowHealth;
  logger: typeof logger;
  macroTriggers: typeof macroTriggers;
  macros: typeof macros;
  marketplace: typeof marketplace;
  "migrations/backfillAccountMembers": typeof migrations_backfillAccountMembers;
  "migrations/backfillCommandActions": typeof migrations_backfillCommandActions;
  "migrations/backfillSharedMacros": typeof migrations_backfillSharedMacros;
  moderation: typeof moderation;
  moduleAssets: typeof moduleAssets;
  moduleDetail: typeof moduleDetail;
  moduleEngine: typeof moduleEngine;
  moduleFunctions: typeof moduleFunctions;
  moduleIntegrationState: typeof moduleIntegrationState;
  moduleManifestSync: typeof moduleManifestSync;
  moduleOAuth: typeof moduleOAuth;
  moduleRepository: typeof moduleRepository;
  moduleResourceActions: typeof moduleResourceActions;
  moduleResourceInstances: typeof moduleResourceInstances;
  moduleSettingsActions: typeof moduleSettingsActions;
  moduleWebhook: typeof moduleWebhook;
  moduleWidgets: typeof moduleWidgets;
  oauthConnectHandoff: typeof oauthConnectHandoff;
  obsStatus: typeof obsStatus;
  pageIntros: typeof pageIntros;
  pins: typeof pins;
  platformRealtime: typeof platformRealtime;
  previewEngine: typeof previewEngine;
  provisioning: typeof provisioning;
  provisioningInternal: typeof provisioningInternal;
  registration: typeof registration;
  resourceKinds: typeof resourceKinds;
  resourceValues: typeof resourceValues;
  resources: typeof resources;
  sceneActions: typeof sceneActions;
  sceneWidgets: typeof sceneWidgets;
  scenes: typeof scenes;
  "seeds/triggerActions": typeof seeds_triggerActions;
  setup: typeof setup;
  setupApply: typeof setupApply;
  setupPlatforms: typeof setupPlatforms;
  setupPlatformsActions: typeof setupPlatformsActions;
  shoutouts: typeof shoutouts;
  spotifyConnect: typeof spotifyConnect;
  spotifyIntegration: typeof spotifyIntegration;
  starterPacks: typeof starterPacks;
  storage: typeof storage;
  streamInfo: typeof streamInfo;
  streamRecap: typeof streamRecap;
  streamSessionSummaries: typeof streamSessionSummaries;
  streamStatus: typeof streamStatus;
  supporters: typeof supporters;
  transientEvents: typeof transientEvents;
  triggerDefinitions: typeof triggerDefinitions;
  twitchAuth: typeof twitchAuth;
  twitchBroadcast: typeof twitchBroadcast;
  twitchClips: typeof twitchClips;
  twitchIntegration: typeof twitchIntegration;
  users: typeof users;
  webhookAuth: typeof webhookAuth;
  workflowActions: typeof workflowActions;
  workflowCatalog: typeof workflowCatalog;
  workflowCatalogContext: typeof workflowCatalogContext;
  workflowHealth: typeof workflowHealth;
  workflowInternal: typeof workflowInternal;
  workflowRuns: typeof workflowRuns;
  workflows: typeof workflows;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
