/** Twitch OAuth scopes for Settings → Integrations connect (not sign-in). */
export const TWITCH_INTEGRATION_SCOPES = [
  "user:read:email",
  "user:bot",
  "user:write:chat",
  "user:read:chat",
  "chat:read",
  "chat:edit",
  "bits:read",
  "channel:manage:broadcast",
  "channel:moderate",
  "channel:read:hype_train",
  "channel:read:polls",
  "channel:read:predictions",
  "channel:read:redemptions",
  "channel:read:subscriptions",
  "clips:edit",
  "moderator:manage:blocked_terms",
  "moderator:manage:shoutouts",
  "moderator:manage:banned_users",
  "moderator:read:chatters",
  "moderator:read:chat_messages",
  "moderator:read:chat_settings",
  "moderator:read:followers",
  "moderator:read:moderators",
  "moderator:read:unban_requests",
  "moderator:read:warnings",
  "moderator:read:vips",
] as const;
