// Run with: bun script/generate-lucide-aliases.ts
// Regenerate after upgrading lucide-react; lucide-names.test.ts fails while
// the committed file is out of date.
//
// lucide-react exports every renamed icon under its old names too, and stored
// macro and catalog icon names may use them. dynamicIconImports only has the
// canonical names, so this records which canonical icon each old name is.

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { kebabToPascal } from "../client/src/lib/lucide-names";

const ROOT = path.resolve(import.meta.dirname, "..");
const LUCIDE_ENTRY = path.join(ROOT, "node_modules/lucide-react/dist/esm/lucide-react.js");
const ALIASES_FILE = path.join(ROOT, "client/src/lib/lucide-aliases.generated.ts");

const EXPORT_LINE = /export \{([^}]*)\} from '\.\/icons\/([a-z0-9-]+)\.js';/g;
const EXPORTED_NAME = /default as (\w+)/g;

/** Each icon's kebab-case file name, to every name lucide-react exports it under. */
export function readLucideExports(): Map<string, string[]> {
  const source = readFileSync(LUCIDE_ENTRY, "utf8");
  const icons = new Map<string, string[]>();
  for (const [, names, kebab] of source.matchAll(EXPORT_LINE)) {
    icons.set(
      kebab,
      [...names.matchAll(EXPORTED_NAME)].map(([, name]) => name)
    );
  }
  if (icons.size === 0) {
    throw new Error(`no Lucide icon exports found in ${LUCIDE_ENTRY}; its export format has changed`);
  }
  return icons;
}

/** Old PascalCase name to the canonical kebab-case icon name, sorted by old name. */
export function readLucideAliases(): Record<string, string> {
  const aliases: Array<[string, string]> = [];
  for (const [kebab, names] of readLucideExports()) {
    const canonical = kebabToPascal(kebab);
    for (const name of names) {
      const isVariant = name.startsWith("Lucide") || name.endsWith("Icon");
      if (!isVariant && name !== canonical) {
        aliases.push([name, kebab]);
      }
    }
  }
  if (aliases.length === 0) {
    throw new Error(`no Lucide aliases found in ${LUCIDE_ENTRY}; its export format has changed`);
  }
  aliases.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  return Object.fromEntries(aliases);
}

export function renderAliasesModule(aliases: Record<string, string>): string {
  const entries = Object.entries(aliases)
    .map(([name, kebab]) => `  ${name}: "${kebab}",`)
    .join("\n");
  return [
    "// Generated by script/generate-lucide-aliases.ts. Do not edit.",
    "",
    "export const LUCIDE_ALIASES: Readonly<Record<string, string>> = {",
    entries,
    "};",
    "",
  ].join("\n");
}

if (import.meta.main) {
  writeFileSync(ALIASES_FILE, renderAliasesModule(readLucideAliases()));
  console.log(`wrote ${ALIASES_FILE}`);
}
